### ISSUE TITLE
Error with XBMC Eden

### ISSUE THREAD

**Issue by brainwave9** [colszowka/xbmc-client#1]
I'm testing xbmc-client with the latest Eden beta, which has a slightly changed JSON API.
I get the following error:

xbmc-client/lib/xbmc-client.rb:39:in `commands': undefined method`map' for nil:NilClass (NoMethodError)
        from /root/GitSiriProxy/xbmc-client/lib/xbmc-client.rb:46:in `load_api!'
        from example_environment.rb:8:in`<main>'

If I run it with an Dharma setup, it works just fine.
The script is your example_environment.rb, I only modified ip, port, username and password

**Comment by antoinerg** [comment]
Can confirm there is problem with Eden as well. I love this gem BTW. Would be nice if this was fixed! Thank you
