### ISSUE TITLE
Bundler::GemfileNotFound: Could not locate Gemfile  

### ISSUE THREAD

**Issue by maddox** [colszowka/xbmc-client#7]
Not sure whats up with this, but the gem won't load and this is the error:

```

/opt/github/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/bundler-1.2.3/lib/bundler/shared_helpers.rb:22:in `default_gemfile': Could not locate Gemfile (Bundler::GemfileNotFound)
    from /opt/github/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/bundler-1.2.3/lib/bundler.rb:222:in `default_gemfile'
    from /opt/github/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/bundler-1.2.3/lib/bundler.rb:173:in `root'
    from /opt/github/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/bundler-1.2.3/lib/bundler.rb:179:in `app_config_path'
    from /opt/github/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/bundler-1.2.3/lib/bundler.rb:191:in `settings'
    from /opt/github/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/bundler-1.2.3/lib/bundler.rb:330:in `configure_gem_home_and_path'
    from /opt/github/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/bundler-1.2.3/lib/bundler.rb:86:in `configure'
    from /opt/github/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/bundler-1.2.3/lib/bundler.rb:142:in `definition'
    from /opt/github/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/bundler-1.2.3/lib/bundler.rb:112:in `setup'
    from /opt/github/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/bundler-1.2.3/lib/bundler.rb:128:in `require'
    from /opt/github/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/xbmc-client-0.1.2/lib/xbmc-client.rb:4:in `<top (required)>'
    from /opt/github/rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
    from /opt/github/rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
    from /opt/github/rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    from xbmc.rb:2:in `<main>'
```

**Comment by colszowka** [comment]
This should be fixed in the current git master branch, haven't pushed a new release to rubygems in ages, mostly since this was originally built against XBMC Dharma (v10) and needs a lot of work catch up with the improvements to the JSONRPC API made in XBMC Eden and Frodo (in particular the JSONRPC.Introspect method now includes detailed info on what kind of request/return values are available).

The current git master should have basic stuff working against Eden/Frodo though.
